def checkOs(){
    if (isUnix()) {
        sh "export NODE_ENV=qaCred"
    }
    else {
        sh "set NODE_ENV=qaCred"
    }
}

version: 2.1
jobs:
  installDependencies:
    docker:
      - image: "node:14"
    steps:
      - run:
          command: npm install
  setEnvironment:
    docker:
      - image: "node:14"
      # auth:
      #     username: user_username
      #     password: user_password

    steps:
      - run:
          command: checkOs()
  parallelExecution:
    docker:
      - image: "node:14"
  
    steps:
      - checkout
      - run:
          command: npm test
workflows:
  version: 2
  build-and-test:
    jobs:
      - installDependencies
      - setEnvironment:
          requires:
            - installDependencies
      - parallelExecution:
          requires:
            - setEnvironment

            


