version: 2.1
jobs:
  build:
    docker:
      - image: "node:14"
      # auth:
      #     username: user_username
      #     password: user_password

    steps:
      - run:
          command: echo "Building the project"
  test:
    docker:
      - image: "node:14"
      # auth:
      #     username: user_username
      #     password: user_password

    steps:
      - run:
          command: echo "Testing the project"
  run:
    docker:
      - image: "node:14"
      # auth:
      #     username: user_username
      #     password: user_password

    steps:
      - checkout
      - run:
          command: node main
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - run:
          requires:
            - test


