# version: 2.1
# orbs: 
#   os-detect: circleci/os-detect@0.3.0
# jobs:
#   installDependencies:
#     docker:
#       - image: "node:14"
#     steps:
#       - run:
#           command: npm install
#   setEnvironment:
#     docker:
#       - image: "node:14"
#     steps:
#       - detect/init
#       - run: 'echo "The current operating system  is ${OSD_ID}"'
          
#   parallelExecution:
#     docker:
#       - image: "node:14"
#     steps:
#       - checkout
#       - run:
#           command: npm test
# workflows:
#   version: 2
#   build-and-test:
#     jobs:
#       - installDependencies
#       - setEnvironment:
#           requires:
#             - installDependencies
#       - parallelExecution:
#           requires:
#             - setEnvironment
version: 2.1
orbs: 
  detect: circleci/os-detect@0.3.0
jobs:
  installDep:
    docker:
      - image: "node:14"
    steps:
      - run: npm install
  setEnv:
    docker:
      - image: cibuilds/base
    steps:
      - detect/init
      - run: 'echo "The current operating system is ${OSD_FAMILY}."' 
                  
workflows:
  version: 2
  build-and-test:
    jobs:
      - installDep
      - setEnv:
          requires:
             - installDep

